version: '2'
services:
  web:
    image:          nginx:latest
    container_name: nginx
    restart:        always
    ports:
      - "8080:80"
  volumes:
    - ./www:       /www
    - ./site.conf: /etc/nginx/conf.d/site.conf
